### ISSUE TITLE
enable dependabot & security monitoring

### ISSUE THREAD

**Issue by rursprung** [dsldevkit/dsl-devkit#240]
i have no personal experience with this, but based on the docu it seems a good idea:

* set up the automated security monitoring: https://help.github.com/en/articles/configuring-automated-security-fixes
* enable dependabot which automatically offers dependency updates whenever it finds that some are available: https://github.com/marketplace/dependabot-preview

**Comment by rubenporras** [comment]
Hi @rursprung ,

thanks for the hint. I have enabled Dependabot, let us see how it works for us.
