### ISSUE TITLE
Questions regarding Semantic Predicates

### ISSUE THREAD

**Issue by tobixdev** [dsldevkit/dsl-devkit#369]
Hi!

I hope it is ok to open an issue here just to ask a question. 

We have an existing Xtext project for which we want to make the DSL more conscise. For this reason we would need semantic predicates which Xtext does unfortunately not support. After being pointed to your repository by @knutwannheden (thanks again) I came across the [PR](https://github.com/dsldevkit/dsl-devkit/pull/174/files) which introduced semantic predicates in the dsl-devkit.

I have some questions before starting to introduce the semantic predicates in our project. It would be really helpful if someone could help me out.

Firstly, I am a little bit concerned as to how Xtext will handle these newly introduced predicates. Are there any major changes required in Xtext itself, or will it work perfectly fine with the new ANTLR grammars? And if it will work, which limitations are introduced. I already saw the [issue](https://github.com/dsldevkit/dsl-devkit/issues/210) mentioning semantic coloring and content assist.

Secondly, I read in a [forum post](https://www.eclipse.org/forums/index.php?t=msg&th=1069632) that there are problems with predicate hoisting. Did you find a nice solution to this issue?

I know its much to ask, but it would help me alot if someone could share his/her experience regarding this topic. Thanks! 😃

**Comment by gerdleon** [comment]
Hi,
Sorry for the late reply.
Tomorrow, I will check with the team here at Avaloq regarding semantic predicates to give a better answer than my initial "try to avoid them/use them only as a last resort" :-) . In the end it you will have to implement custom behaviors for things that (more or less) come out of the box: content assist, colouring and formatting.
Please stay tuned.

**Comment by rubenporras** [comment]
Hi @tobixdev,

sorry for the very late reply, I guess you are no longer interested in an answer, but I still would like to give you one, even not very thorough.

The semantic predicates work quite well with Xtext, provided you have our extensions, we use it extensively to model very complex languages, like PL/SQL. It is though not complete, as it cannot handle some complex grammar rules, this means that typically one need to inspect the generated ANTLR code or test if the predicate is called, and if it is not the expected, fix the DDK extension to handle the case and inject the predicate at the right place.

Systax coloring works quite well (at least I never noticed a probrem), but it is true that some features like coding completion or serialization do have problems with it. We did not implement that part.

Regards

**Comment by rubenporras** [comment]
Hi @tobixdev , I will close the issue. Please, reopen again if you still have questions.
