### ISSUE TITLE
Check developers should be able to bulk-apply quickfixes

### ISSUE THREAD

**Issue by GrahamPearsonAvaloq** [dsldevkit/dsl-devkit#38]
**Feature (What):**
It should be possible to bulk-apply quickfixes to Checks.

**Reason (Why):**
So that customers can quick-fix many identical errors/warnings at once.

**How to Demo:**
1. Add "@SeverityRange(error..info)" to two Checks. This should cause an error in each Check.
2. In the Problems view, select Group By > Type
3. In the Problems view, expand the Check Problem group. Error "Severity 'info' must precede 'error'" should appear twice.
4. Select both instances of "Severity 'info' must precede 'error'".
5. Right-click and select Quick Fix
6. It should be possible to fix both errors at once in this way.

**Comment by knutwannheden** [comment]
If this issue requires a lot of work, we should decide when to do the Xtext upgrade. Because in the latest release they added support for exactly this.

**Comment by GrahamPearsonAvaloq** [comment]
In principle, it's all done apart from the code reviews. Everything is working fine on my local machine.

In practice, I'm getting failures on Travis in tests which pass for me locally, and which I'm not aware of having touched!

**Comment by GrahamPearsonAvaloq** [comment]
Fixed and tested :-)
